name: Deploy to GitHub Pages

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
